---
- name: change selinux state
  selinux:
    policy: targeted
    state: permissive
  become: yes

- name: stop and disable firewalld
  service:
    name: firewalld
    state: stopped
    enabled: no
  become: yes

- name: put yum repo of kubernetes
  copy:
    src: virt7-docker-common-release.repo 
    dest: /etc/yum.repos.d/virt7-docker-common-release.repo
  become: yes

- name: install packages
  yum:
    name: "{{ item }}"
    state: installed
  become: yes
  with_items:
    - kubernetes
    - etcd
    - flannel
    - python-rhsm

- name: put hosts
  template:
    src: hosts.j2
    dest: /etc/hosts
  become: yes

